packages:
  - 'packages/*'

catalog:
  # Vue 核心及官方插件
  vue: ^3.5.33
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.2

  # TypeScript 及构建工具
  typescript: ^5.9.3
  vue-tsc: ^3.2.7
  '@types/node': ^20.19.27
  unplugin-auto-import: ^0.17.5
  rimraf: ^6.1.2
  move-file-cli: ^3.0.0

  # 工具库与类型
  lodash-es: ^4.18.1
  '@types/lodash-es': ^4.17.12

  # 样式处理
  postcss: ^8.5.3
  postcss-nested: ^6.2.0

  # FontAwesome 图标库
  '@fortawesome/fontawesome-svg-core': ^7.1.0
  '@fortawesome/free-brands-svg-icons': ^7.1.0
  '@fortawesome/free-regular-svg-icons': ^7.1.0
  '@fortawesome/free-solid-svg-icons': ^7.1.0
  '@fortawesome/vue-fontawesome': ^3.1.2

  # 测试套件
  vitest: ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16

overrides:
  '@isaacs/brace-expansion@<=5.0.0': ^5.0.1
  'ajv@>=7.0.0-alpha.0 <8.18.0': ^8.18.0
  'brace-expansion@>=2.0.0 <2.0.3': ^2.0.3
  'diff@>=6.0.0 <8.0.3': ^8.0.3
  'flatted@<=3.4.1': ^3.4.2
  'lodash@<=4.17.23': ^4.18.1
  'minimatch@<3.1.3': '3.1.3'
  'minimatch@>=9.0.0 <9.0.7': ^9.0.7
  'minimatch@>=10.0.0 <10.2.3': ^10.2.3
  'picomatch@<2.3.2': ^2.3.2
  'picomatch@>=4.0.0 <4.0.4': ^4.0.4
  'postcss@<8.5.10': ^8.5.12
  'preact@>=10.28.0 <10.28.2': ^10.28.2
  'rollup@>=4.0.0 <4.59.0': ^4.59.0
  'vitepress>vite': ^6.4.2